export enum CsvValueName {
  EnterpriseFlag = "EnterpriseFlag",
  RecordNumber = "RecordNumber",
  MSACode = "MSACode",
  CensusTract = "CensusTract",
  TractIncomeRatio = "TractIncomeRatio",
  BorrowerIncomeRatio = "BorrowerIncomeRatio",
  LTV = "LTV",
  PurposeOfLoan = "PurposeOfLoan",
  FederalGuarantee = "FederalGuarantee",
  BorrowerRace = "BorrowerRace",
  CoBorrowerRace = "CoBorrowerRace",
  BorrowerGender = "BorrowerGender",
  CoBorrowerGender = "CoBorrowerGender",
  NumberOfUnits = "NumberOfUnits",
  UnitAffordabilityCategory = "UnitAffordabilityCategory",
  RaceComparison = "RaceComparison",
  BorrowerRaceGenderComparison = "BorrowerRaceGenderComparison",
}
